spring.application.name=auth-service

# Server Port
server.port=8081

# Correct JDBC URL format
spring.datasource.url=jdbc:postgresql://ep-super-king-a15c7mhv-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# Correct username and password
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xZTise1Y2QcO

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=auth-group
spring.kafka.consumer.auto-offset-reset=earliest

# Logging (optional)
logging.level.org.springframework.security=DEBUG