spring.application.name=order-service

# Server Port
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/retail_order_db
spring.datasource.username=postgres
spring.datasource.password=Snfp2025*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
