spring.application.name=product-service

# Server Port
server.port=8083

# Database Configuration - Update with your Neon database credentials
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_rlfTgxVIa4j6@ep-floral-moon-a8tr26xb-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rlfTgxVIa4j6

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.security=DEBUG

# Swagger UI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
